#!/usr/bin/env python3
"""
📱 Test Telegram Bot - اختبار البوت يدوياً
"""

import requests
import json

# Telegram Bot credentials
BOT_TOKEN = "7959152691:AAFHoaaD7Mdlpna24E9Ke1z7oLiztzNbbOQ"
CHAT_ID = "207250173"

def test_telegram_connection():
    """اختبار الاتصال مع Telegram Bot"""
    print("📱 Testing Telegram Bot Connection...")
    print(f"Bot Token: {BOT_TOKEN[:20]}...")
    print(f"Chat ID: {CHAT_ID}")
    print("=" * 50)
    
    # Test 1: Get bot info
    try:
        url = f"https://api.telegram.org/bot{BOT_TOKEN}/getMe"
        response = requests.get(url, timeout=10)
        
        if response.status_code == 200:
            bot_info = response.json()
            if bot_info.get('ok'):
                print("✅ Bot connection successful!")
                print(f"   Bot name: {bot_info['result']['first_name']}")
                print(f"   Username: @{bot_info['result']['username']}")
            else:
                print("❌ Bot API error:", bot_info)
        else:
            print(f"❌ HTTP error: {response.status_code}")
            
    except Exception as e:
        print(f"❌ Connection error: {e}")
    
    print()

def send_test_message():
    """إرسال رسالة تجريبية"""
    print("📤 Sending test trading signal...")
    
    # محاكاة إشارة تداول
    message = """🚨 **BOOKMAP AI TRADING SIGNAL** 🚨

💹 **Symbol:** EURUSD
📈 **Direction:** BULLISH  
🎯 **Pattern:** STRONG_SIGNAL
💯 **Confidence:** 78.5%

📊 **Trading Levels:**
   Entry: 1.0850
   Stop Loss: 1.0830 (-20 pips)
   Take Profit: 1.0890 (+40 pips)
   Risk/Reward: 1:2.0

🔧 **Active Tools:**
   ✅ CVD: 85%
   ✅ Heatmap: 78% 
   ✅ Volume Profile: 88%
   ✅ VWAP: 75%

⏰ Time: NY_OPEN
💼 Position: MEDIUM
🤖 Pattern ID: TEST_001

Generated by BookmapAI System 🚀"""

    try:
        url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
        payload = {
            'chat_id': CHAT_ID,
            'text': message,
            'parse_mode': 'Markdown'
        }
        
        response = requests.post(url, json=payload, timeout=10)
        
        if response.status_code == 200:
            result = response.json()
            if result.get('ok'):
                print("✅ Test message sent successfully!")
                print(f"   Message ID: {result['result']['message_id']}")
                print(f"   Date: {result['result']['date']}")
            else:
                print("❌ Send message error:", result)
        else:
            print(f"❌ HTTP error: {response.status_code}")
            print("Response:", response.text)
            
    except Exception as e:
        print(f"❌ Send error: {e}")

def main():
    print("🤖 BookmapAI Telegram Bot Test")
    print("=" * 40)
    
    # Test connection
    test_telegram_connection()
    
    # Send test message
    send_test_message()
    
    print("\n🎯 Test Results:")
    print("1. ✅ Check bot connection status above")
    print("2. ✅ Check your Telegram for test message")  
    print("3. ✅ If successful, BookmapAI notifications should work!")
    
    print(f"\n📱 Check Telegram chat: https://t.me/c/{CHAT_ID}")

if __name__ == "__main__":
    main() 