package com.bookmaai.core;

import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import java.net.*;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * 📱 Telegram Signal Sharing Service
 * Shares trading signals to +21696543589
 */
public class TelegramSignalSharing {
    
    private static final String SIGNAL_CHAT_ID = "+21696543589";
    private static final String BOT_TOKEN = System.getProperty("telegram.bot.token", "");
    private static final String API_URL = "https://api.telegram.org/bot" + BOT_TOKEN + "/sendMessage";
    
    private final ExecutorService executor;
    private final AtomicLong signalsSent = new AtomicLong(0);
    private final AtomicBoolean isEnabled = new AtomicBoolean(true);
    
    public TelegramSignalSharing() {
        this.executor = Executors.newFixedThreadPool(2);
        
        System.out.println("📱 [TelegramSignals] Signal sharing initialized for " + SIGNAL_CHAT_ID);
    }
    
    /**
     * Share a trading signal
     */
    public void shareSignal(TradingSignal signal) {
        if (!isEnabled.get() || BOT_TOKEN.isEmpty()) {
            System.out.println("📱 [TelegramSignals] Signal sharing disabled or bot token missing");
            return;
        }
        
        executor.submit(() -> {
            try {
                String message = formatSignalMessage(signal);
                sendTelegramMessage(message);
                signalsSent.incrementAndGet();
                
                System.out.println("📱 [TelegramSignals] Signal shared: " + signal.getSymbol() + " " + signal.getAction());
                
            } catch (Exception e) {
                System.err.println("❌ [TelegramSignals] Failed to share signal: " + e.getMessage());
            }
        });
    }
    
    /**
     * Share pattern detection alert
     */
    public void sharePatternAlert(String patternType, String symbol, double confidence, String analysis) {
        if (!isEnabled.get() || BOT_TOKEN.isEmpty()) return;
        
        executor.submit(() -> {
            try {
                String message = formatPatternMessage(patternType, symbol, confidence, analysis);
                sendTelegramMessage(message);
                signalsSent.incrementAndGet();
                
                System.out.println("📱 [TelegramSignals] Pattern alert shared: " + patternType + " on " + symbol);
                
            } catch (Exception e) {
                System.err.println("❌ [TelegramSignals] Failed to share pattern alert: " + e.getMessage());
            }
        });
    }
    
    /**
     * Share market analysis
     */
    public void shareMarketAnalysis(String analysis) {
        if (!isEnabled.get() || BOT_TOKEN.isEmpty()) return;
        
        executor.submit(() -> {
            try {
                String message = "📊 **BookmapAI Market Analysis**\n\n" + analysis + 
                               "\n\n🤖 *Generated by BookmapAI with GPT-4*\n" +
                               "⏰ " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                
                sendTelegramMessage(message);
                signalsSent.incrementAndGet();
                
                System.out.println("📱 [TelegramSignals] Market analysis shared");
                
            } catch (Exception e) {
                System.err.println("❌ [TelegramSignals] Failed to share analysis: " + e.getMessage());
            }
        });
    }
    
    private String formatSignalMessage(TradingSignal signal) {
        StringBuilder sb = new StringBuilder();
        sb.append("🚀 **BookmapAI Trading Signal**\n\n");
        sb.append("📈 **Symbol:** ").append(signal.getSymbol()).append("\n");
        sb.append("🎯 **Action:** ").append(signal.getAction()).append("\n");
        sb.append("💰 **Entry:** ").append(String.format("%.5f", signal.getEntryPrice())).append("\n");
        sb.append("🛑 **Stop Loss:** ").append(String.format("%.5f", signal.getStopLoss())).append("\n");
        sb.append("🎯 **Take Profit:** ").append(String.format("%.5f", signal.getTakeProfit())).append("\n");
        sb.append("📊 **R:R Ratio:** ").append(String.format("%.2f", signal.getRiskRewardRatio())).append("\n");
        sb.append("🔥 **Confidence:** ").append(signal.getConfidence()).append("%\n");
        
        if (signal.getPatternType() != null) {
            sb.append("🎯 **Pattern:** ").append(signal.getPatternType()).append("\n");
        }
        
        if (signal.getAnalysis() != null) {
            sb.append("\n📝 **Analysis:**\n").append(signal.getAnalysis()).append("\n");
        }
        
        sb.append("\n⏰ ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        sb.append("\n🤖 *Generated by BookmapAI with GPT-4*");
        
        return sb.toString();
    }
    
    private String formatPatternMessage(String patternType, String symbol, double confidence, String analysis) {
        StringBuilder sb = new StringBuilder();
        sb.append("🎯 **Pattern Detected**\n\n");
        sb.append("📊 **Pattern:** ").append(patternType).append("\n");
        sb.append("💱 **Symbol:** ").append(symbol).append("\n");
        sb.append("🔥 **Confidence:** ").append(String.format("%.1f", confidence)).append("%\n");
        
        if (analysis != null && !analysis.isEmpty()) {
            sb.append("\n📝 **Analysis:**\n").append(analysis).append("\n");
        }
        
        sb.append("\n⏰ ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        sb.append("\n🤖 *BookmapAI Pattern Detection*");
        
        return sb.toString();
    }
    
    private void sendTelegramMessage(String message) throws Exception {
        if (BOT_TOKEN.isEmpty()) {
            throw new Exception("Telegram bot token not configured");
        }
        
        // Prepare request body
        String requestBody = "chat_id=" + URLEncoder.encode(SIGNAL_CHAT_ID, "UTF-8") +
                           "&text=" + URLEncoder.encode(message, "UTF-8") +
                           "&parse_mode=Markdown";
        
        // Use Java 8 compatible HTTP connection
        URL url = new URL(API_URL);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("POST");
        connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
        connection.setDoOutput(true);
        connection.setConnectTimeout(10000);
        connection.setReadTimeout(30000);
        
        // Send request
        try (OutputStream os = connection.getOutputStream()) {
            byte[] input = requestBody.getBytes("UTF-8");
            os.write(input, 0, input.length);
        }
        
        // Read response
        int responseCode = connection.getResponseCode();
        if (responseCode != 200) {
            String errorResponse = "";
            try (BufferedReader br = new BufferedReader(new InputStreamReader(
                    responseCode >= 400 ? connection.getErrorStream() : connection.getInputStream(), "UTF-8"))) {
                StringBuilder response = new StringBuilder();
                String responseLine;
                while ((responseLine = br.readLine()) != null) {
                    response.append(responseLine.trim());
                }
                errorResponse = response.toString();
            }
            throw new Exception("Telegram API returned status: " + responseCode + 
                              ", body: " + errorResponse);
        }
    }
    
    public void enable() { isEnabled.set(true); }
    public void disable() { isEnabled.set(false); }
    public boolean isEnabled() { return isEnabled.get(); }
    public long getSignalsSent() { return signalsSent.get(); }
    
    public void shutdown() {
        executor.shutdown();
        try {
            if (!executor.awaitTermination(5, TimeUnit.SECONDS)) {
                executor.shutdownNow();
            }
        } catch (InterruptedException e) {
            executor.shutdownNow();
        }
    }
    
    // Trading Signal class
    public static class TradingSignal {
        private final String symbol;
        private final String action; // BUY or SELL
        private final double entryPrice;
        private final double stopLoss;
        private final double takeProfit;
        private final int confidence;
        private final String patternType;
        private final String analysis;
        
        public TradingSignal(String symbol, String action, double entryPrice, 
                           double stopLoss, double takeProfit, int confidence) {
            this(symbol, action, entryPrice, stopLoss, takeProfit, confidence, null, null);
        }
        
        public TradingSignal(String symbol, String action, double entryPrice, 
                           double stopLoss, double takeProfit, int confidence, 
                           String patternType, String analysis) {
            this.symbol = symbol;
            this.action = action;
            this.entryPrice = entryPrice;
            this.stopLoss = stopLoss;
            this.takeProfit = takeProfit;
            this.confidence = confidence;
            this.patternType = patternType;
            this.analysis = analysis;
        }
        
        public String getSymbol() { return symbol; }
        public String getAction() { return action; }
        public double getEntryPrice() { return entryPrice; }
        public double getStopLoss() { return stopLoss; }
        public double getTakeProfit() { return takeProfit; }
        public int getConfidence() { return confidence; }
        public String getPatternType() { return patternType; }
        public String getAnalysis() { return analysis; }
        
        public double getRiskRewardRatio() {
            double risk = Math.abs(entryPrice - stopLoss);
            double reward = Math.abs(takeProfit - entryPrice);
            return risk > 0 ? reward / risk : 0.0;
        }
    }
}
